# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Kathy Beyer Photography"
description: "Powered by Jekyll and GitHub Pages"
author:      "Kathy Beyer"
background-image: url('/img/background.jpg')
